### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NameError' and 'int'

### ISSUE THREAD

**Issue by jimboca** [BioSehnsucht/pyelk#5]
traceback_print is throwing an error when connection is lost during startup?

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/serial/threaded/__init__.py", line 211, in run
    self.protocol.connection_lost(error)
  File "./PyElk/Connection/__init__.py", line 39, in connection_lost
    traceback.print_exc(exc)
  File "/usr/local/lib/python3.6/traceback.py", line 159, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/local/lib/python3.6/traceback.py", line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/usr/local/lib/python3.6/traceback.py", line 497, in __init__
    capture_locals=capture_locals)
  File "/usr/local/lib/python3.6/traceback.py", line 332, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'NameError' and 'int'
```

**Comment by BioSehnsucht** [comment]
This is abandoned. Please use https://github.com/gwww/elkm1 / https://pypi.org/project/elkm1-lib/
