### ISSUE TITLE
Exception when thread is stopped

### ISSUE THREAD

**Issue by jimboca** [BioSehnsucht/pyelk#7]
```
2019-11-04 20:54:57,560 [Thread-5  ] [ERROR] Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/pi/.local/lib/python3.5/site-packages/serial/threaded/__init__.py", line 211, in run
    self.protocol.connection_lost(error)
  File "/home/pi/.local/lib/python3.5/site-packages/PyElk/Connection/__init__.py", line 37, in connection_lost
    self._pyelk._connection._connection_output.stop()
AttributeError: 'NoneType' object has no attribute '_connection_output'
```

**Comment by BioSehnsucht** [comment]
This is abandoned. Please use https://github.com/gwww/elkm1 / https://pypi.org/project/elkm1-lib/
